package com.boutique.notification.service;
import tools.jackson.databind.ObjectMapper;import org.slf4j.*;import org.springframework.amqp.rabbit.annotation.RabbitListener;import org.springframework.beans.factory.annotation.Value;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.kafka.annotation.KafkaListener;import org.springframework.mail.SimpleMailMessage;import org.springframework.mail.javamail.JavaMailSender;import org.springframework.stereotype.Component;import java.time.Duration;
@Component
public class DomainEventNotificationListener{
 private static final Logger log=LoggerFactory.getLogger(DomainEventNotificationListener.class);private final ObjectMapper json;private final JavaMailSender mail;private final StringRedisTemplate redis;private final String from,to;private final Duration dedupeTtl;
 public DomainEventNotificationListener(ObjectMapper json,JavaMailSender mail,StringRedisTemplate redis,@Value("${notification.email.from:no-reply@boutique.local}")String from,@Value("${notification.email.default-recipient:demo.customer@boutique.local}")String to,@Value("${notification.dedupe-ttl:7d}")Duration ttl){this.json=json;this.mail=mail;this.redis=redis;this.from=from;this.to=to;this.dedupeTtl=ttl;}
 @KafkaListener(topics={"${app.kafka.order-events-topic}","${app.kafka.payment-events-topic}","${app.kafka.shipping-events-topic}"},groupId="${spring.kafka.consumer.group-id}")public void kafka(String payload)throws Exception{handle(payload,"kafka");}
 @RabbitListener(queues="boutique.notification.events")public void rabbit(String payload)throws Exception{handle(payload,"rabbitmq");}
 private void handle(String payload,String transport)throws Exception{var e=json.readTree(payload);String eventId=e.path("eventId").asText();if(eventId.isBlank())throw new IllegalArgumentException("Notification event is missing eventId");String key="notification:processed:"+eventId;Boolean claimed=redis.opsForValue().setIfAbsent(key,"1",dedupeTtl);if(!Boolean.TRUE.equals(claimed)){log.info("NOTIFICATION_DUPLICATE_SKIPPED transport={} eventId={}",transport,eventId);return;}try{String type=e.path("eventType").asText();String order=e.path("orderId").asText();log.info("NOTIFICATION eventType={} orderId={} transport={} eventId={}",type,order,transport,eventId);SimpleMailMessage m=new SimpleMailMessage();m.setFrom(from);m.setTo(to);m.setSubject("Boutique update: "+type);m.setText("Event: "+type+"\nOrder: "+order+"\nTransport: "+transport+"\n\nThis is a local demo notification.");mail.send(m);}catch(Exception failure){redis.delete(key);throw failure;}}
}
