package com.boutique.notification.service;

import tools.jackson.databind.JsonNode;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
public class EmailNotificationService {
    private final JavaMailSender mail;
    private final String defaultRecipient;
    private final String from;

    public EmailNotificationService(
            JavaMailSender mail,
            @Value("${notification.email.default-recipient:demo.customer@boutique.local}") String defaultRecipient,
            @Value("${notification.email.from:no-reply@boutique.local}") String from) {
        this.mail=mail; this.defaultRecipient=defaultRecipient; this.from=from;
    }

    public void send(JsonNode event,String source) {
        String type=event.path("eventType").asText("BOUTIQUE_EVENT");
        String orderId=event.path("orderId").asText("n/a");
        SimpleMailMessage message=new SimpleMailMessage();
        message.setFrom(from);
        message.setTo(defaultRecipient);
        message.setSubject("Boutique update: "+type.replace('_',' '));
        message.setText("""
            Boutique Demo Commerce Platform

            Event: %s
            Order: %s
            Source: %s
            Status: %s

            This message was generated by the local production-like email service.
            No real payment or email provider was used.
            """.formatted(type,orderId,source,event.path("status").asText("n/a")));
        mail.send(message);
    }
}
